language: node_js
node_js:
  - "node"
script:
  - npm install codecov -g
  - karma start ./test-config/karma.conf.js --single-run
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
after_success:
  - codecov
